#!/bin/bash
# Program to create and maintain a text journal from command line.

#Function to record an entry
recordEntry()
{
	date +%d/%m/%y			#Echo the date in DD/MM/YYYY format
	date +%A			#Echo the day of the Week
	echo ">>"
	read -r ENTRY
	date +%d/%m/%y >> $FILE		#Add date header to log entry
	date +%A >> $FILE		#Add day-of-week header to log entry
	echo "$ENTRY" >> $FILE		#Log the actual entry
}

#Function to set a tag preceding an entry
setTag()
{
	echo "TAG=""$TAG" >> $FILE	#Add a tag header to log entry
	echo "TAG=""$TAG"			#Debug echo
}

#Function to list entries with specific tag
listTag()
{
	true	#placeholder			#Add function to search for, aggregate and list them 
}

#Initial default for log file
FILE="captainslog.txt"

#Main switch statement that drives program
case "$1" in 
	"-t")	#Apply a tag
		shift
		TAG="$1"
		echo "$TAG"
		setTag
		recordEntry
		;;
	"-l")	#List a tag
		shift
		listTag
		;;
	"-f")	#Use a different file than default
		shift
		FILE="$1"
		recordEntry
		;;
	*)	#Default statement if no tags specified
		echo "Entry for $(date +%d/%m/%y):"
		recordEntry
		;;
esac
	echo >> $FILE
	cat $FILE			#Debug - list entire log file.
